### ISSUE TITLE
Add to dotnet tools repo

### ISSUE THREAD

**Issue by lindexi** [ivanparvaresh/dotnet-exec#18]
Suggestion: Add to https://github.com/natemcmaster/dotnet-tools

**Comment by ivanparvaresh** [comment]
@lindexi Thanks for your suggestion
The PR created. 
https://github.com/natemcmaster/dotnet-tools/pull/191

**Comment by ivanparvaresh** [comment]
[PR](https://github.com/natemcmaster/dotnet-tools/pull/192) accepted
