### ISSUE TITLE
`name` is required

### ISSUE THREAD

**Issue by justin-caldicott** [ivanparvaresh/dotnet-exec#39]
But I'm not sure what it's for. I just set mine to `"."`.

Can it's purpose be documented and/or it made optional?

**Comment by ivanparvaresh** [comment]
@justin-caldicott could you explain the issue a little bit more?

**Comment by justin-caldicott** [comment]
In the `.dotnetexec.json` file there's a required `name` property. I'm not sure what this is for, but it's required. I'm not sure what putting the solution name in there gives us, as in the readme. I'd prefer to not have the property if it's not needed for anything.

**Comment by ivanparvaresh** [comment]
added to the board
