### ISSUE TITLE
Should traverse up directories looking for `dotnetexec` file

### ISSUE THREAD

**Issue by justin-caldicott** [ivanparvaresh/dotnet-exec#41]
I was hoping we'd be able to exec from any folder in the repo, but I only appear to be able to exec from the root of the repo, in the folder where the `dotnetexec` file lives.

It would be great if it traversed up the directory tree looking for the file, like e.g. the `dotnet-tools.json` itself.

**Comment by ivanparvaresh** [comment]
@justin-caldicott Thanks, Added to the board
